title: The world of fashion typography
description: ""
header_text: ""
footer_text: Copyright 2020 Marie Henriksen
header_feature_image: ../uploads/yes.jpg
bannerheight: 20vmax
logo: ../uploads/logo.jpg
favicon: ../uploads/android-chrome-192x192.png
gridlayout: false
fixednavbar: false
upzoom: false
items: []
